### ISSUE TITLE
Reset control value when switching to velocity mode

### ISSUE THREAD

**Issue by Kam0ss** [sonia-auv/rqt_sonia_plugins#16] opened 2020-02-23 02:26 UTC

**Comment by marcantoinecouture** [comment] 2020-02-23 04:21
I verified and the problem is not in the widget, but in the control. 
See [issue #10 in proc_control](https://github.com/sonia-auv/proc_control/issues/10)
I'm closing this issue

**Closed as completed by marcantoinecouture** 2020-02-23 04:21 UTC
Labels: Priority: Critical, Type: Bug
